version: '3'
services:
  web:
    container_name: ${container_web_name}
    build:
      dockerfile: Dockerfile
      context: custom-fpm
    ports:
      - "80:80"
    volumes:
#      - "./custom-fpm/nginx.conf:/etc/nginx/nginx.conf"
      - "./custom-fpm/nginx-m1.conf:/etc/nginx/nginx.conf"
#      - "./custom-fpm/nginx-m2.conf:/etc/nginx/nginx.conf"
      - "./custom-fpm/php.ini:/etc/php/7.1/fpm/php.ini"
      - "./magento:/var/www/public"
      - "./custom-fpm/log:/var/log/nginx"
  mysql:
    container_name: ${container_mysql_name}
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
#      volumes:
#      - "./custom-fpm/data/magento:/var/lib/mysql/magento"